### ISSUE TITLE
Persistent springs

### ISSUE THREAD

**Issue by borisschapira** [nhoizey/esviji#130]
Chrome, Android : springs never disappear.

**Comment by borisschapira** [comment]
![screenshot_2015-12-29-08-21-28](https://cloud.githubusercontent.com/assets/284742/12030918/fe7c4cac-ae05-11e5-88f5-2feb972e9a7a.png)

**Comment by nhoizey** [comment]
:-/

Thanks

**Comment by nhoizey** [comment]
Two questions:
- Can you confirm there is only one spring in the DOM (id "playableSpring") before throwing the ball?
- Can you tell me if there is a "Now erasing spring…" message in the console when you throw the ball?

Thanks.

**Comment by borisschapira** [comment]
* Several playableSpring
* Message is written in the console

![capture d ecran 2015-12-31 a 08 35 09](https://cloud.githubusercontent.com/assets/284742/12062276/733e1022-af99-11e5-9b2e-391a9ff3c78a.png)

**Comment by borisschapira** [comment]
In fact I have only one `playableSpring` before starting the game. When I throw a ball, the spring disappear from the screen and the `playableSpring` too, from the code.
When it's my turn again, several (from 6 to 15) `playableSpring` appear in code.

I've tried playing a little... the number of `playableSprint` varies a lot :

![capture d ecran 2015-12-31 a 08 42 48](https://cloud.githubusercontent.com/assets/284742/12062315/810cdb06-af9a-11e5-947d-a820878bc948.png)

**Comment by borisschapira** [comment]
In fact the number of `playableSpring`increment when I touch no balls (from 1 to 3) and when I touch balls, depending of how many balls I've touched and if I've rebound before...

**Comment by nhoizey** [comment]
Reaaaaaly strange! ;-)

Thanks for the detailed tests, I'll try to find how it can generate so many springs…

**Comment by borisschapira** [comment]
:+1:

**Comment by nhoizey** [comment]
\o/

But #133 … :-/
