### ISSUE TITLE
No sound in Chrome Android

### ISSUE THREAD

**Issue by nhoizey** [nhoizey/esviji#135]
Reported by @borisschapira

**Comment by borisschapira** [comment]
Two OGG loaded in the Network tab, then, message in the console : "Can't load sound effects…"

**Comment by nhoizey** [comment]
No issue with ogg/vorbis support in Chrome for Android, at least: http://caniuse.com/#feat=ogg-vorbis

**Comment by borisschapira** [comment]
Unable to read directly http://v2.esviji.com/sounds/effects-sprite.ogg on my phone so I suspect a Codec issue.

**Comment by nhoizey** [comment]
Has it ever worked on your device?

Do sounds play in esviji v1?

**Comment by borisschapira** [comment]
It has worked, but does not work any more, neither in v1 nor v2.

**Comment by nhoizey** [comment]
Wow, ok.

With same Android/Chrome?

**Comment by nhoizey** [comment]
Can you try these tests? http://hpr.dogphilosophy.net/test/

**Comment by borisschapira** [comment]
Yep ! No issue on the same Android w/ Firefox.

-- 
Boris Schapira - *http://borisschapira.com <http://borisschapira.com/>*
Tél : +33 6 64 42 92 14

**Comment by borisschapira** [comment]
* opus : :heavy_check_mark: 
* weba : :heavy_check_mark: 
* ogg : :heavy_check_mark: 
* wav : :heavy_check_mark: 
* mp3 : :heavy_check_mark: 
* flac : :heavy_check_mark:

**Comment by borisschapira** [comment]
Still no sound but two error message now : 

* Can't load sound effects…
* Can't load ambiance sound…

**Comment by nhoizey** [comment]
Whoops, didn't want to close the issue, only link to it from the commit…

**Comment by nhoizey** [comment]
Only Firefox works on Android 5.1: https://twitter.com/ClovisGauzy/status/684164183345229824

**Comment by webaaz** [comment]
Android lolipop client twitter bbb esviji audio test

This browser supports ogg/vorbis audio.

This browser supports MP3 audio.

Can't load sound.

**Comment by webaaz** [comment]
Android lolipop chrome à jour
esviji audio test

This browser supports ogg/vorbis audio.

This browser supports MP3 audio.

Can't load sound.

**Comment by webaaz** [comment]
Android lolipop firefox à jouresviji audio test

This browser supports ogg/vorbis audio.

This browser supports MP3 audio.

Sound loaded.

Sound playing.

Par contre ça charge une musique qui va pas du tout avec le jeu... ;-)

**Comment by zemax** [comment]
Android 6.0.1, Chrome 47 :

esviji audio test

This browser supports ogg/vorbis audio.

This browser supports MP3 audio.

Can't load sound.

**Comment by nhoizey** [comment]
Thanks a lot @webaaz and @zemax !

It seems there is really an issue with Chrome on Android, then.

@webaaz la musique ne te semble pas adaptée ? Elle était prévue en fond sonore du jeu, mais pas encore mise…

**Comment by borisschapira** [comment]
![test2](https://cloud.githubusercontent.com/assets/284742/12112519/52354316-b39d-11e5-9ee3-e08e3cb1ea38.png)

Nouveaux tests : deux échecs. "Can't load sound" pour les deux.

**Comment by nhoizey** [comment]
:-/

**Comment by borisschapira** [comment]
Moi j'aime bien la musique mais je me demande comment ça va rendre avec les différents bips au touché des boules.

**Comment by nhoizey** [comment]
Je ne sais pas trop non plus, il faut que j'essaie vraiment, j'ai aussi des doutes…

**Comment by webaaz** [comment]
Faut voir en situation, je la trouvait un peu oppressante, j'aurais vu un truc plus calme, mais essaie qu'on se rende mieux compte

**Comment by nhoizey** [comment]
New URL for tests: http://v2.esviji.com/tests/

Could you try again in Chrome/Android?

**Comment by borisschapira** [comment]
Nope, still no success :/

**Comment by nhoizey** [comment]
So it seems adding WebM audio to the show fixed the issue! \o/
